export const projectsData = [
  {id: 1, img: "./UW.webp", title: "Upwork", type: "Freelance", date: "May 2021 - Present", description: "A Top Rated Freelancer at Upwork, an American freelancing platform and the largest network of independent professionals to get things done, from quick turnarounds to big transformations.", link: "https://www.upwork.com/freelancers/~01c12e516ee1d35044/"},
  {id: 2, img: "./Lounge.webp", title: "Lounge", type: "Freelance", date: "May 2021 - Present", description: "Developed features for the web & native app which took the app from launch to 90,000 monthly active users. Was awarded with a 5-Star review and the following testimonial: “Tap is an exceptional software engineer. He worked in my team for nearly a year, and consistently performed to an extremely high level. In particular his strengths are his attitude, speed to output, intellectual curiosity and ability to learn new things. I can't recommend Tap highly enough!”.", link: "https://lounge.live/login"},
  {id: 3, img: "./Replai.webp", title: "Replai", type: "Freelance", date: "May 2021 - Present", description: "Developed the entire UI Library for Replai, a Multi-Million Dollar Startup that leverages AI and Machine Vision to make better creative decisions at scale.", link: "https://www.replai.io/"},
  {id: 4, img: "./Clyde.webp", title: "Clyde.ai", type: "Freelance", date: "May 2021 - Present", description: "Clyde is a AI powered Web Application which automatically calculates the value of rewards you'd earn based on your transaction data. Collaborated with the team to develop the Clyde Web Application.", link: "https://bestcreditcard.com/"},
  {id: 5, img: "./EF.webp", title: "Element Finance", type: "Freelance", date: "May 2021 - Present", description: "Created the Component Library for Element Finance and was awarded a 5 Star Review for the final product and the following Testimonial: Tapajyoti was great and not only completed the job to the best of his ability but under the alotted time and budget! He was quick to communicate about issues and think on his feet. Great to work with!", link: "https://delv.tech/"},
  {id: 6, img: "./CR.webp", title: "Chirrup", type: "Freelance", date: "May 2021 - Present", description: "Built the Dashboard UI and was awarded a 5 Star Review for the final product and the following Testimonial: “Amazing front-end developer. Tap helped build out our web app and will add value to any future project he works on. Works quickly. Easily adaptable. And helped form solutions to problems that popped up along the way. We'd happily hire him again.”.", link: "https://www.chirrup.chat/"},
  {id: 7, img: "./HJ.webp", title: "Homejam", type: "Freelance", date: "May 2021 - Present", description: "Developed the payment confirmation page and a plethora of bug fixes for HomeJam Web App, an application delivering virtual concerts like you’ve never experienced before."},
  {id: 8, img: "./SM.webp", title: "Smartsapp", type: "Personal Project", date: "May 2021 - Present", description: "With SmartsApp, you'll get fast and simple messaging secured with End to End Encryption for free, available on the web, all android & iOS phones, and Windows, Linux & macOS computers all over the world. Used Diffie-Hellman Key Exchange algorithm to generate the shared keys & XOR Cipher to encrypt messages. The tech stack consisted of React, Redux, Electron, Flutter & Firebase.", link: "https://www.versaihq.com/", github: "https://github.com/ruppysuppy/SmartsApp"},
  {id: 9, img: "./UW.webp", title: "The algorithms", type: "Open source Maintainer", date: "May 2021 - Present", description: "Maintaining and Adding New Algorithms to the code base of the world's largest Open Source resource for learning Data Structures & Algorithms and their implementation in any Programming Language.", link: "https://smartsapp-ba40f.firebaseapp.com/login", github: "https://github.com/TheAlgorithms"},
  {id: 10, img: "./HF.webp", title: "Hactober fest 2020", type: "Open source", date: "May 2021 - Present", description: "Created Quality Pull Requests in the celebration of the Open Source Spirit at Hacktoberfest, a month-long celebration of open source software run by DigitalOcean in partnership with GitHub and Twilio.", link: "https://the-algorithms.com/"},
  {id: 11, img: "./UW.webp", title: "Unhook", type: "Personal Project", date: "May 2021 - Present", description: "If you are one of the rare breed of people who call themselves programmers, you must have faced the following situation: You were so busy working, that you forgot to take a break from coding... now your eyes hurt due to the excessive stress on them. The solution? Use UnHook, an app that helps you unhook yourself from the screen by reminding you to take breaks at the right time. The tech stack consisted of React, Redux & Electron.", link: "https://hacktoberfest.com/", github: "https://github.com/ruppysuppy/UnHook"},
  {id: 12, img: "./PM.webp", title: "Pizza man", type: "Personal Project", date: "May 2021 - Present", description: "Pizza Man is always open to serve you. Order all your favorite pizzas from the comfort of your home, and we will ensure free delivery for all orders. The tech stack consisted of React & Redux.", link: "https://pizza-man-61510.firebaseapp.com/", github: "https://github.com/ruppysuppy/Pizza-Man"},
  {id: 13, img: "./PM.webp", title: "Weather man", type: "Personal Project", date: "May 2021 - Present", description: "Weather Man has local and international weather forecasts from the most accurate weather forecasting technology featuring up-to-the-minute weather reports. The tech stack consisted of Python & Django along with Open Weather API, Chart.js & AOS.", link: "https://campus24.in/"},
  {id: 14, img: "./C24.webp", title: "campus 24", type: "Internship", date: "May 2021 - Present", description: "Developed the landing page and worked on the web application of Campus 24, a tech startup aiming to revolutionize the interconnections between college departments by fueling collaboration, entrepreneurial spirit, talent development, learning experience, and team spirit."},
  {id: 15, img: "./DCP.webp", title: "Daily coding problems", type: "Personal Projects", date: "May 2021 - Present", description: "Solved 350+ interview problems from Daily Coding Problem, a mailing list for coding interview problems asked at FAANG and other top tech companies.", github: "https://github.com/ruppysuppy/Pizza-Man"},
]



export const blogsData = [
  {id: 1, link: "https://dev.to/ruppysuppy/7-javascript-web-apis-to-build-futuristic-websites-you-didnt-know-38bc", img: "./blog1.png", title: "7 JavaScript Web APIs to build Futuristic Websites you didn't know🤯", date: "Sun Feb 19 2023", skills: ["webdev", "javascript", "html", "beginners"], likes: 819, comments: 51},
  {id: 2, link: "https://dev.to/ruppysuppy/7-free-public-apis-you-will-love-as-a-developer-166p", img: "./blog2.webp", title: "7 Free Public APIs you will love as a developer💖", date: "Sun Feb 05 2023", skills: ["javascript", "webdev", "programming", "api"], likes: 994, comments: 26},
  {id: 3, link: "https://dev.to/ruppysuppy/7-shorthand-optimization-tricks-every-javascript-developer-should-know-4fj5", img: "./blog3.png", title: "7 Shorthand Optimization Tricks every JavaScript Developer Should Know 😎", date: "Sun Oct 30 2022", skills: ["javascript", "webdev", "programming", "productivity"], likes: 923, comments: 56},
  {id: 4, link: "https://dev.to/ruppysuppy/mastering-these-7-basics-css-skills-will-make-you-a-frontend-wizard-2khn", img: "./blog4.png", title: "Mastering these 7 Basics CSS Skills will make you a Frontend Wizard 🧙✨", date: "Sun Seb 11 2023", skills: ["webdev", "javascript", "html", "beginners"], likes: 624, comments: 15},
  {id: 5, link: "https://dev.to/ruppysuppy/the-regular-expression-regex-cheat-sheet-you-always-wanted-1c8h", img: "./blogs/blog5.jpg", title: "The Regular Expression (RegEx) Cheat Sheet you always wanted", date: "Sun Aug 14 2022", skills: ["webdev", "javascript", "html", "beginners"], likes: 938, comments: 14},
  {id: 6, link: "https://dev.to/ruppysuppy/grid-vs-flex-where-to-use-which-3g0p", img: "./blog6.jpg", title: "Grid vs Flex: Where to use which? 🤔", date: "Sun Jul 24 2022", skills: ["webdev", "javascript", "html", "beginners"], likes: 574, comments: 10},
]